item {
  id: 1
  name: 'Tkrlk'
}

item {
  id: 2
  name: 'EkYol'
}

item {
  id: 3
  name: 'YtyCtlk'
}

item {
  id: 4
  name: 'YtyBrlsm'
}

item {
  id: 5
  name: 'Timsah'
}

item {
  id: 6
  name: 'Ckr'
}

item {
  id: 7
  name: 'YayaGecidi'
}

item {
  id: 8
  name: 'YolCizgisi'
}
